baseURL = 'https://stackandsignal.com/'
languageCode = 'en-us'
title = 'Stack & Signal'
theme = 'stackandsignal'

[params]
  description = "Projects, thoughts, and random things I'm working on."
  
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Newsletter"
    url = "/newsletter/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3