baseURL = 'https://stackandsignal.com/'
languageCode = 'en-us'
title = 'Stack & Signal'
theme = 'stackandsignal'

[pagination]
  pagerSize = 10

[params]
  description = "A website about marketing technology, side projects, and building things on the internet."
  
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Newsletter"
    url = "/newsletter/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3